version: '3.8'

services:
  app1:
    build: ./app1
    container_name: flask_app1

  app2:
    build: ./app2
    container_name: flask_app2

  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2

